### ISSUE TITLE
System libs cmake switches

### ISSUE THREAD

**Issue by SCOTT-HAMILTON** [magiruuvelvet/OTPGen#5]
# Issue template

Thanks for using my software. If you think you found a bug or experience
a problem make sure to work through this checklist first.

*For feature suggestions ignore this list.*

 - [x] Operating System
 - [ ] Compiler
 - [ ] CMake version
 - [ ] CMake build options used and the console output
 - [ ] When using the GUI: version of Qt
 - [ ] zlib: bundled or shared
 - [ ] QR Code Support enabled?

 - [ ] A description of the issue
 - [ ] If possible, how to reproduce the problem

I'm packaging OTPGen for NixOS [here](https://github.com/NixOS/nixpkgs/pull/87887) and it would be much preferred if we could have the choice of using system libs instead of  the bundled libs (with cmake options for example).

**Comment by magiruuvelvet** [comment]
Note that some of the libraries where modified and are out of sync with upstream. Some libraries are for unit tests only and sqlite is not used in the latest tagged release which works, the current master is not usable.

For the boost abomination I may consider replacing it with the C++17 filesystem library instead. But this software is currently not maintained by me actively. boost is only used in the CLI version which I think doesn't work at all - only the GUI. The migration tool is also pretty useless as I stopped working on the new GUI.

I will think about it.

EDIT: I just checked the CLI, it only asks for the password and decrypts the database and exits immediately. No functionality implemented at all.

EDIT2: The only thing I noticed which can have an optimal cmake switch is the QtKeychain integration. That one is not modified except its CMake files.

**Comment by magiruuvelvet** [comment]
qt keychain can now be compiled against the shared version using a cmake switch

**Comment by magiruuvelvet** [comment]
zlib has a cmake switch to build it against the shared version

**Comment by SCOTT-HAMILTON** [comment]
Have you modified cereal? I can't build with the systems one. But maybe the systems one is not well packaged.

**Comment by SCOTT-HAMILTON** [comment]
It has been pointed out that zxing-cpp is unmaintained and therefore should be replaced by a more mainstream, more maintained library such as zbar.

**Comment by magiruuvelvet** [comment]
cereal just could be heavily outdated in my repo. Don't know if they introduced breaking changes in the past 2 years. Note that OTPGen isn't maintained either, it's in support only mode so I'm not really motivated to change the QR Code backend. Sorry about that.

During adding the new cmake switch I already found another problem with Qt. I used undocumented private APIs and now OTPGen fails to build in Qt 5.14, that's about what I'm fixing. Changing the QR Code backend is just too much work.

**Comment by jtojnar** [comment]
Regarding cereal, as I understand the error:

```
In file included from /build/source/Source/Core/AppSupport/Authy.cpp:10:
/nix/store/6ky93idh7ms4rsin1dy26jf1fywh7dzr-cereal-1.3.0/include/cereal/external/rapidxml/rapidxml.hpp:88:36: error: expected ';' at end of member declaration
   88 |         virtual const char *what() const CEREAL_NOEXCEPT override
      |                                    ^~~~~
      |                                         ;
/nix/store/6ky93idh7ms4rsin1dy26jf1fywh7dzr-cereal-1.3.0/include/cereal/external/rapidxml/rapidxml.hpp:88:42: error: 'CEREAL_NOEXCEPT' does not name a type
   88 |         virtual const char *what() const CEREAL_NOEXCEPT override
      |                                          ^~~~~~~~~~~~~~~
/nix/store/6ky93idh7ms4rsin1dy26jf1fywh7dzr-cereal-1.3.0/include/cereal/external/rapidxml/rapidxml.hpp:88:29: error: looser throw specifier for 'virtual const char* cereal::rapidxml::parse_error::what() const'
   88 |         virtual const char *what() const CEREAL_NOEXCEPT override
      |                             ^~~~
```

Either the `rapidxml.hpp` is internal header and then OTPGen should not use it, or https://github.com/USCiLab/cereal/commit/70754e2cab41754b21dbc43e6ff697179a031315 should have added include of cereal's `macros.hpp`.

**Comment by magiruuvelvet** [comment]
The bundled cereal version is 2 years old which works. Just tried the current master and I get this exact error.

I adapted to the new cereal version. I included header files from the external directory directly instead of using the wrapper.

**Comment by jtojnar** [comment]
Looks like it is already reported: https://github.com/USCiLab/cereal/issues/482

**Comment by magiruuvelvet** [comment]
One question to the NixOS packagers. Does the NixOS package format require a release tag or can it be a branch name or commit hash too? I now made a `stable` branch with all the fixes and updates. This should make it way easier for packagers.

**Comment by jtojnar** [comment]
We can work with commits too, we use `unstable-yyyy-mm-dd` as a version then. Targetting non-default branch might be slightly confusing but adding a comment to the package expression would fix that.

**Comment by SCOTT-HAMILTON** [comment]
Waiting https://github.com/magiruuvelvet/OTPGen/issues/7 for further packaging, closing this issue.
